name: QEMU Build cndrvcups-capt for ARM

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为编译环境

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 QEMU 模拟 ARM 环境
      - name: Set up QEMU for ARM
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static binfmt-support

      # 3. 设置 ARM 环境
      - name: Set up ARM environment
        run: |
          sudo mkdir -p /usr/arm-linux-gnueabihf
          sudo apt update
          sudo apt install -y libcups2-dev:armhf libxml2-dev:armhf gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      # 4. 交叉编译驱动
      - name: Build cndrvcups-capt
        run: |
          export CC=arm-linux-gnueabihf-gcc
          export CXX=arm-linux-gnueabihf-g++
          cd cndrvcups-capt
          make

      # 5. 打包编译结果
      - name: Package build artifacts
        run: |
          mkdir -p artifacts
          cp -r cndrvcups-capt/* artifacts/
          tar -czvf cndrvcups-capt-arm-build.tar.gz artifacts

      # 6. 上传编译结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cndrvcups-capt-arm-build
          path: cndrvcups-capt-arm-build.tar.gz
