name: Docker Buildx cndrvcups-capt for ARM

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为编译环境

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Docker 环境并启用 Buildx
      - name: Set up Docker with Buildx
        run: |
          sudo apt update
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo docker buildx create --use

      # 3. 使用 Docker Buildx 构建 ARM 环境并编译驱动
      - name: Build cndrvcups-capt with Docker Buildx
        run: |
          sudo docker buildx build --platform linux/arm64 -t cndrvcups-capt-builder -f - . <<EOF
          FROM arm64v8/ubuntu:20.04
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt update && apt install -y build-essential libcups2-dev libxml2-dev tzdata
          COPY . /workspace
          WORKDIR /workspace/cndrvcups-capt
          RUN make
          EOF

      # 4. 提取编译结果
      - name: Extract build artifacts
        run: |
          mkdir -p artifacts
          sudo docker run --rm -v $(pwd)/artifacts:/output cndrvcups-capt-builder bash -c "cp -r /workspace/cndrvcups-capt/* /output/"
          tar -czvf cndrvcups-capt-arm-build.tar.gz artifacts

      # 5. 上传编译结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cndrvcups-capt-arm-build
          path: cndrvcups-capt-arm-build.tar.gz
