name: Build Canon LBP2900 Driver for ARM

on:
  workflow_dispatch:  # 启用手动触发
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 打印 Hello World
      - name: Run a simple script
        run: echo "Hello, World!"
