name: Docker Build cndrvcups-capt for ARM

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为编译环境

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Docker 环境
      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      # 3. 使用 Docker 构建 ARM 环境并编译驱动
      - name: Build cndrvcups-capt in Docker
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace arm32v7/ubuntu:20.04 bash -c "
            apt update &&
            apt install -y build-essential libcups2-dev libxml2-dev &&
            cd cndrvcups-capt &&
            make
          "

      # 4. 打包编译结果
      - name: Package build artifacts
        run: |
          mkdir -p artifacts
          cp -r cndrvcups-capt/* artifacts/
          tar -czvf cndrvcups-capt-arm-build.tar.gz artifacts

      # 5. 上传编译结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cndrvcups-capt-arm-build
          path: cndrvcups-capt-arm-build.tar.gz
