name: Cross Build cndrvcups-capt for ARM

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为编译环境

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置交叉编译环境
      - name: Set up cross-compilation environment
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libcups2-dev:armhf libxml2-dev:armhf

      # 3. 交叉编译驱动
      - name: Cross-build cndrvcups-capt
        run: |
          export CC=arm-linux-gnueabihf-gcc
          export CXX=arm-linux-gnueabihf-g++
          cd cndrvcups-capt
          make

      # 4. 打包编译结果
      - name: Package build artifacts
        run: |
          mkdir -p artifacts
          cp -r cndrvcups-capt/* artifacts/
          tar -czvf cndrvcups-capt-arm-build.tar.gz artifacts

      # 5. 上传编译结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cndrvcups-capt-arm-build
          path: cndrvcups-capt-arm-build.tar.gz
